name: dart_downloader
description: A Dart library for downloading files from the internet with pause, resume and cancel features.
version: 0.0.2+1
homepage: https://github.com/Crazelu/dart_downloader

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.5
  path_provider: ^2.0.14
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

